# Generated by Django 3.1.2 on 2020-10-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_auto_20200708_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
